##\u914D\u7F6E\u8BBF\u95EE\u7AEF\u53E3
server:
  port: 8082

spring:
  thymeleaf:
    mode: HTML
    cache: true
    encoding: utf-8
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weifx?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "0000"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml
